/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdjustmentSlider: typeof import('./src/components/AdjustmentSlider.vue')['default']
    FilterPresetSelector: typeof import('./src/components/FilterPresetSelector.vue')['default']
    ImageAdjustments: typeof import('./src/components/ImageAdjustments.vue')['default']
    ImageCropper: typeof import('./src/components/ImageCropper.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview.vue')['default']
    ImageUploadDropzone: typeof import('./src/components/ImageUploadDropzone.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VCol: typeof import('vuetify/components')['VCol']
    VContainer: typeof import('vuetify/components')['VContainer']
    VFadeTransition: typeof import('vuetify/components')['VFadeTransition']
    VFileInput: typeof import('vuetify/components')['VFileInput']
    VIcon: typeof import('vuetify/components')['VIcon']
    VMain: typeof import('vuetify/components')['VMain']
    VRow: typeof import('vuetify/components')['VRow']
    VSlider: typeof import('vuetify/components')['VSlider']
    VSpacer: typeof import('vuetify/components')['VSpacer']
  }
}
